### ISSUE TITLE
Accompanying text for "threads" chapter is out of sync with code

### ISSUE THREAD

**Issue by jhrcek** [typeclasses/haskell-phrasebook#1]
Thank you for this wonderful project!

The text at https://typeclasses.com/phrasebook/threads talks about stderr, which is not used at all in the example code, which is a bit confusing:

> Setting the stderr output stream’s buffer mode to line-buffering will make the output of this example more readable.

**Comment by jhrcek** [comment]
One more minor wart: this page shows incorrect breadcrumb at the top ("timeouts" instead of expected "transactions")
https://typeclasses.com/phrasebook/transactions

![Screenshot from 2019-08-10 11-33-45](https://user-images.githubusercontent.com/2716069/62820318-f26e1300-bb62-11e9-9e6b-f6535db2f6c2.png)

**Comment by chris-martin** [comment]
Oops, thank you for the corrections! Both errors are fixed now :smile:
