### ISSUE TITLE
Reducing a list to a single value

### ISSUE THREAD

**Issue by chris-martin** [typeclasses/haskell-phrasebook#2]
It might be nice to put this page right after [mutable references](https://typeclasses.com/phrasebook/mutable-references) and show how some loops involving mutation can be written as folds, like [this Rust page](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold) does.

If this page is limited to `base`, it might use `fold`, `foldMap`, and `foldl'`.

We could also consider using the [foldl](https://hackage.haskell.org/package/foldl) package if there's a significant benefit. The `average` example [in the docs](https://hackage.haskell.org/package/foldl-1.4.5/docs/Control-Foldl.html) seems somewhat compelling. I'm not sure what the right tradeoff is here between the extra high-level expressivity of `Control.Foldl` versus having to introduce another thing.

**Comment by JonathanLorimer** [comment]
Hey @chris-martin I would be happy to tackle this issue

**Comment by friedbrice** [comment]
I'm happy to pick this one up. Let me try to think of some non-contrived examples.

**Comment by argumatronic** [comment]
I think this was also the goal of PR #20. 

Was there a particular reason for listing `foldl'` but not `foldr`? I feel like we talked about this at some point but cannot remember.

**Comment by chris-martin** [comment]
I don't remember why we left this issue open, I think https://typeclasses.com/phrasebook/folding-lists has the folding basics covered.
