### ISSUE TITLE
[Book] Chapter "enum ranges" is missing next link

### ISSUE THREAD

**Issue by andys8** [typeclasses/haskell-phrasebook#37]
Hey, I noticed "enum ranges" is missing a link to the next chapter. The previous chapters had this. Thanks for the book.

https://typeclasses.com/phrasebook/enum-ranges

![Screenshot_20191125-143239](https://user-images.githubusercontent.com/13085980/69544777-baaf9d80-0f90-11ea-80d9-743990f5edf2.png)

**Comment by chris-martin** [comment]
Fixed (a while ago) :smile:
