### ISSUE TITLE
[nix-shell] moving build output from the sandbox to the Nix store: Permission denied

### ISSUE THREAD

**Issue by lambiase** [typeclasses/haskell-phrasebook#38]
When running

```
nix-shell tools/shell.nix
```

I get (on a Debian and on an Ubuntu machine on which I have freshly installed nix):

```
...
building '/nix/store/d7wmn4239kg32jv0i4y600nxdl2a0v3v-alex-plan-to-nix-pkgs.drv'...
error: moving build output '/nix/store/cx2gfhixdiv6kxdlijj7ifn29mvqy6sl-alex-plan-to-nix-pkgs' from the sandbox to the Nix store: Permission denied
```

Is anyone else having the same issue?

**Comment by chris-martin** [comment]
I haven't seen this before, but I suspect something is wrong with your Nix installation. Is Nix not working at all, or is it just this repository?

**Comment by lambiase** [comment]
nix-shell in general seems to work fine (however I don't have too much experience with the nix package manager).

I can consistently reproduce the issue as follows:
- create a new Ubuntu 18.04 VM
- install nix (as a normal user) with `curl -L https://nixos.org/nix/install | sh`
- clone https://github.com/typeclasses/haskell-phrasebook
- execute `nix-shell tools/shell.nix`

It looks like it's a nix bug:
https://github.com/NixOS/nix/issues/2984

which is also mentioned here:
https://github.com/input-output-hk/haskell.nix/issues/466

@chris-martin : are you using a different OS or an older version of nix?

**Comment by lambiase** [comment]
After following the "Multi User Installation" instructions (https://nixos.org/nix/manual/#sect-multi-user-installation) I don't get the permission denied error anymore, confirming that it's a nix bug affecting single user installations only.
